/*
 * This source file was generated by the Gradle 'init' task
 */
package org.prayer;
import java.util.Scanner;

public class App {
    public String start() {
		Init init = new Init();
		System.out.println(init.getHeader());
		System.out.println(init.getBibleVerse());
		/*
		Scanner scanner = new Scanner(System.in);
		System.out.println("Write your entry.  End it with ->Enter->Enter->Enter");
		String entry = scanner.nextLine();
		*/
		return "Testing";
    }

    public static void main(String[] args) {
        System.out.println(new App().start());
    }
}
